### PR TITLE
normalizePath - fixes #16, fixes #18

### LINKED ISSUE #18: Fsproj file doesn't get found - Path starts with slash
I'm running into the following error:
image

The path to the project start with a slash which is kind of strange.

Any idea how to solve that?

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

File: src/Helpers.fs [hunk 1]
```diff
@@ -12,6 +12,15 @@ module Helpers
 
         let inline ignore promise = Promise.map ignore promise
 
+    module IO =
+        let dirSeparator = Fable.Import.Node.Exports.path.sep
+
+        let inline normalizePath(path:string) =
+            (if path.Contains(":") then path.TrimStart '/' else path)
```
Comment (forki) [inline src/Helpers.fs:19]: /cc @Krzysztof-Cieslak @MangelMaxime is this correct on nix?
